### ISSUE TITLE
sql file request

### ISSUE THREAD

**Issue by drogozhang** [thilan-tran/restock#2]
great repo!
I was wondering could you provide the SQL construction file? If so, I would be very grateful.

**Comment by thilan-tran** [comment]
Hi, thanks so much!

I'm not exactly sure what you mean by the SQL construction file. In this project I relied heavily on Flask-SQLAlchemy to abstract most of the barebones SQL and database details, using this [quick start guide](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/).

`restock/__init__.py` initializes the database according to a URI, and then `manage.py` imports all my models and uses Flask-SQLAlchemy to create the database. 

All I had to do externally was specify a database URI for SQLAlchemy to use in my `.env`, which was a sqlite path during development and then a Heroku PostgreSQL path in production.

EDIT: I would like to go back at some point and reimplement the backend without the crutch of using a high level SQL library like Flask-SQLAlchemy.
